#!/usr/bin/env ansible-playbook
---
- name: install nginx
  package:
    name: nginx
    state: present
  tags: nginx
  become: True

- name: confirm nginx running
  service:
    name: nginx
    state: started
  tags: nginx
  become: True

- name: who am I
  shell: whoami
  tags: shell  
  