#!/usr/bin/env ansible-playbook
---

- name: provision a vagrant machine
  hosts: localhost
  become: False
  vars:
    box: trusty64    
  tasks:
    - name: create a vagrant file
      command: vagrant init {{ box }} creates=Vagrantfile

    - name: bring up a vagrant machine
      command: vagrant up

    - name: add the vagrant machine to inventory
      add_host:
        name: vagrant
        ansible_host: 127.0.0.1
        ansible_port: 2222
        ansible_user: vagrant
        ansible_private_key_file: /home/min/.vagrant.d/insecure_private_key
        
    - name: check vagrant status
      command: vagrant status